<?php

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_payment_eway_commerce_payment_method_info() {
  return array(
    'commerce_payment_eway' => array(
      'title' => t('eWAY Payment Gateway'),
      'short_title' => t('eWAY'),
      'display_title' => t('Credit card'),
      'description' => t('Provides integration with the eWAY payment gateway.'),
      'active' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function commerce_payment_eway_menu() {
  $items = array();
  return $items;
}

